with open('flask_app/templates/index.html', 'r', encoding='utf-8') as f:
    lines = f.readlines()

clean_lines = lines[:222]

clean_lines.extend([
    '</div>\n',
    '</div>\n',
    '</main>\n',
    '</div>\n',
    '{% endblock %}\n',
    '\n',
    '{% block scripts %}\n',
    '<script>\n',
    'document.addEventListener("DOMContentLoaded", function() {\n',
    '    let activeZ1Load = parseFloat("{{ zone1_load }}");\n',
    '    let activeZ2Load = parseFloat("{{ zone2_load }}");\n',
    '    let activeZ3Load = parseFloat("{{ zone3_load }}");\n',
    '\n',
    '    function updateZoneUI(z1, z2, z3) {\n',
    '        const el1 = document.getElementById("zone1_mw_readout") || document.getElementById("zone1_mw_readout_stable");\n',
    '        if(el1) el1.innerText = z1.toFixed(1);\n',
    '        const el2 = document.getElementById("zone2_mw_readout") || document.getElementById("zone2_mw_readout_stable");\n',
    '        if(el2) el2.innerText = z2.toFixed(1);\n',
    '        const el3 = document.getElementById("zone3_mw_readout") || document.getElementById("zone3_mw_readout_stable");\n',
    '        if(el3) el3.innerText = z3.toFixed(1);\n',
    '    }\n',
    '\n',
    '    const btn = document.getElementById("launchCampaignBtn");\n',
    '    const citizensCount = document.getElementById("citizensCount");\n',
    '    const mwReduced = document.getElementById("mwReduced");\n',
    '    const progressBar = document.getElementById("impactProgressBar");\n',
    '    const targetReduction = document.getElementById("targetReduction");\n',
    '    const zoneSelect = document.getElementById("zoneSelect");\n',
    '    const arrowIcon = document.getElementById("arrowIcon");\n',
    '    let isCampaignRunning = false;\n',
    '    let simulationInterval = null;\n',
    '    const messagePreviewText = document.getElementById("messagePreviewText");\n',
    '\n',
    '    function updateTargetUI() {\n',
    '        let targetMwVal = parseFloat("{{ zone2_target | default(5.0) }}");\n',
    '        let zoneName = "Zone 2";\n',
    '        if(zoneSelect.value === "all") { targetMwVal = parseFloat("{{ all_target | default(12.5) }}"); zoneName = "All Zones"; }\n',
    '        if(zoneSelect.value === "zone1") { targetMwVal = parseFloat("{{ zone1_target | default(4.2) }}"); zoneName = "Zone 1"; }\n',
    '        if(zoneSelect.value === "zone3") { targetMwVal = parseFloat("{{ zone3_target | default(3.8) }}"); zoneName = "Zone 3"; }\n',
    '        targetReduction.innerText = `Target: ${targetMwVal.toFixed(1)} MW Reduction`;\n',
    '        messagePreviewText.innerHTML = `⚠️ <strong>Tetouan City Alert:</strong> Peak energy demand expected in ${zoneName} in 30 mins! Reduce your AC by 2 degrees for 1 hour and earn a 5% discount on your next bill.`;\n',
    '    }\n',
    '\n',
    '    function resetSimulation() {\n',
    '        isCampaignRunning = false;\n',
    '        clearInterval(simulationInterval);\n',
    '        btn.innerHTML = `<span class="material-symbols-outlined group-hover:scale-110 transition-transform">rocket_launch</span> Launch Citizen Challenge Campaign`;\n',
    '        btn.classList.remove("bg-secondary", "bg-error", "opacity-80");\n',
    '        btn.classList.add("bg-primary");\n',
    '        citizensCount.innerText = `Ready to Launch`;\n',
    '        mwReduced.innerText = `0.0`;\n',
    '        progressBar.style.width = `0%`;\n',
    '        arrowIcon.style.display = "none";\n',
    '        updateTargetUI();\n',
    '        updateZoneUI(activeZ1Load, activeZ2Load, activeZ3Load);\n',
    '    }\n',
    '\n',
    '    updateTargetUI();\n',
    '\n',
    '    zoneSelect.addEventListener("change", function() {\n',
    '        resetSimulation();\n',
    '    });\n',
    '\n',
    '    btn.addEventListener("click", function() {\n',
    '        if (isCampaignRunning) { resetSimulation(); return; }\n',
    '        isCampaignRunning = true;\n',
    '        btn.innerHTML = `<span class="material-symbols-outlined animate-spin">sync</span> Launching...`;\n',
    '        btn.classList.add("opacity-80");\n',
    '        setTimeout(() => {\n',
    '            btn.innerHTML = `<span class="material-symbols-outlined">stop_circle</span> Stop Campaign`;\n',
    '            btn.classList.remove("bg-primary");\n',
    '            btn.classList.add("bg-error"); \n',
    '            startSimulation();\n',
    '        }, 800);\n',
    '    });\n',
    '\n',
    '    function startSimulation() {\n',
    '        let currentCitizens = 0;\n',
    '        let currentMw = 0.0;\n',
    '        arrowIcon.style.display = "inline-block";\n',
    '        let targetMwVal = 5.0;\n',
    '        if(zoneSelect.value === "all") targetMwVal = 12.5;\n',
    '        if(zoneSelect.value === "zone1") targetMwVal = 4.2;\n',
    '        if(zoneSelect.value === "zone3") targetMwVal = 3.8;\n',
    '        targetReduction.innerText = `Target: ${targetMwVal.toFixed(1)} MW Reduction`;\n',
    '        const duration = 5000;\n',
    '        const steps = 50;\n',
    '        const intervalTime = duration / steps;\n',
    '        let step = 0;\n',
    '        simulationInterval = setInterval(() => {\n',
    '            step++;\n',
    '            const progress = step / steps;\n',
    '            const easeOutProgress = 1 - Math.pow(1 - progress, 3);\n',
    '            currentCitizens = Math.floor(easeOutProgress * (targetMwVal * 800));\n',
    '            currentMw = easeOutProgress * targetMwVal;\n',
    '            citizensCount.innerText = `Campaign Active: ${currentCitizens.toLocaleString()} Citizens Responding`;\n',
    '            mwReduced.innerText = currentMw.toFixed(1);\n',
    '            progressBar.style.width = `${(currentMw / targetMwVal) * 100}%`;\n',
    '            if(zoneSelect.value === "all") {\n',
    '                updateZoneUI(activeZ1Load - (currentMw * 0.4), activeZ2Load - (currentMw * 0.3), activeZ3Load - (currentMw * 0.3));\n',
    '            } else if(zoneSelect.value === "zone1") {\n',
    '                updateZoneUI(activeZ1Load - currentMw, activeZ2Load, activeZ3Load);\n',
    '            } else if(zoneSelect.value === "zone2") {\n',
    '                updateZoneUI(activeZ1Load, activeZ2Load - currentMw, activeZ3Load);\n',
    '            } else if(zoneSelect.value === "zone3") {\n',
    '                updateZoneUI(activeZ1Load, activeZ2Load, activeZ3Load - currentMw);\n',
    '            }\n',
    '            if (step >= steps) {\n',
    '                clearInterval(simulationInterval);\n',
    '                if(zoneSelect.value === "all") {\n',
    '                    activeZ1Load -= (currentMw * 0.4);\n',
    '                    activeZ2Load -= (currentMw * 0.3);\n',
    '                    activeZ3Load -= (currentMw * 0.3);\n',
    '                } else if(zoneSelect.value === "zone1") {\n',
    '                    activeZ1Load -= currentMw;\n',
    '                } else if(zoneSelect.value === "zone2") {\n',
    '                    activeZ2Load -= currentMw;\n',
    '                } else if(zoneSelect.value === "zone3") {\n',
    '                    activeZ3Load -= currentMw;\n',
    '                }\n',
    '            }\n',
    '        }, intervalTime);\n',
    '    }\n',
    '\n',
    '    const triageCheckboxes = document.querySelectorAll(".triage-checkbox");\n',
    '    const triageTotalSavings = document.getElementById("triageTotalSavings");\n',
    '    const executeTriageBtn = document.getElementById("executeTriageBtn");\n',
    '\n',
    '    if(triageCheckboxes.length > 0 && executeTriageBtn) {\n',
    '        function updateTriageTotal() {\n',
    '            let total = 0;\n',
    '            triageCheckboxes.forEach(cb => {\n',
    '                if(cb.checked) total += parseFloat(cb.dataset.mw);\n',
    '            });\n',
    '            triageTotalSavings.innerText = total.toFixed(1) + " MW";\n',
    '        }\n',
    '        triageCheckboxes.forEach(cb => { cb.addEventListener("change", updateTriageTotal); });\n',
    '        executeTriageBtn.addEventListener("click", function() {\n',
    '            executeTriageBtn.innerHTML = `<span class="material-symbols-outlined animate-spin text-[18px]">sync</span> Executing...`;\n',
    '            executeTriageBtn.disabled = true;\n',
    '            setTimeout(() => {\n',
    '                executeTriageBtn.innerHTML = `<span class="material-symbols-outlined text-[18px]">check_circle</span> Auto-Shed Complete`;\n',
    '                executeTriageBtn.classList.remove("bg-primary", "hover:bg-surface-tint");\n',
    '                executeTriageBtn.classList.add("bg-[#10b981]"); \n',
    '                let totalShed = 0;\n',
    '                triageCheckboxes.forEach(cb => {\n',
    '                    if(cb.checked) totalShed += parseFloat(cb.dataset.mw);\n',
    '                });\n',
    '                {% if zone1_status == "CRITICAL" %} activeZ1Load -= totalShed; {% elif zone2_status == "CRITICAL" %} activeZ2Load -= totalShed; {% elif zone3_status == "CRITICAL" %} activeZ3Load -= totalShed; {% endif %}\n',
    '                updateZoneUI(activeZ1Load, activeZ2Load, activeZ3Load);\n',
    '                const criticalBoxes = document.querySelectorAll(".bg-error-container");\n',
    '                criticalBoxes.forEach(box => {\n',
    '                    box.style.transition = "all 1s ease";\n',
    '                    box.classList.remove("bg-error-container", "border-error");\n',
    '                    box.classList.add("bg-secondary-container", "border-secondary");\n',
    '                    const textEl = box.querySelector(".text-error");\n',
    '                    if (textEl && textEl.innerHTML.includes("CRITICAL")) {\n',
    '                        textEl.innerHTML = textEl.innerHTML.replace(/CRITICAL - \\d+% Capacity/, "Stable");\n',
    '                        textEl.classList.remove("text-error");\n',
    '                        textEl.classList.add("text-secondary");\n',
    '                    }\n',
    '                });\n',
    '                setTimeout(() => {\n',
    '                    const triagePanel = document.getElementById("triagePanel");\n',
    '                    if (triagePanel) {\n',
    '                        triagePanel.style.opacity = "0";\n',
    '                        setTimeout(() => triagePanel.style.display = "none", 500);\n',
    '                    }\n',
    '                }, 3000);\n',
    '            }, 1500);\n',
    '        });\n',
    '    }\n',
    '});\n',
    '</script>\n',
    '{% endblock %}\n'
])

with open('flask_app/templates/index.html', 'w', encoding='utf-8') as f:
    f.writelines(clean_lines)

print('Success')
